export type SkillGroup = {
  id: string;
  label: string;
  emoji: string;
  skills: string[];
};

export const SKILL_GROUPS: SkillGroup[] = [
  {
    id: "elektrik",
    label: "Elektrik & Aydınlatma",
    emoji: "💡",
    skills: [
      "Ampul takma",
      "Avize montajı",
      "Spot aydınlatma montajı",
      "LED şerit montajı",
      "Priz değişimi",
      "Anahtar / düğme değişimi",
      "Sigorta değişimi",
      "Elektrik tesisatı tamiri",
      "Kablo döşeme",
      "Zil / diyafon montajı",
      "Aplik montajı",
      "Elektrikli ısıtıcı kurulumu",
      "Jeneratör kurulumu",
      "Kombi elektrik arızası",
      "Bahçe aydınlatması",
    ],
  },
  {
    id: "tesisat",
    label: "Su & Tesisat",
    emoji: "🚿",
    skills: [
      "Musluk değişimi",
      "Musluk tamiri",
      "Sifon tamiri",
      "Klozet montajı",
      "Lavabo montajı",
      "Duşakabin montajı",
      "Gider açma",
      "Tıkanıklık açma",
      "Su kaçağı tespiti",
      "Petek temizliği",
      "Kombi bakımı",
      "Boyler montajı",
      "Su deposu montajı",
      "Çamaşır makinesi bağlantısı",
      "Bulaşık makinesi bağlantısı",
      "Bahçe sulama sistemi",
    ],
  },
  {
    id: "mobilya",
    label: "Mobilya & Montaj",
    emoji: "🪑",
    skills: [
      "Mobilya montajı",
      "IKEA montajı",
      "Dolap montajı",
      "Gardırop montajı",
      "Yatak / baza montajı",
      "Masa & sandalye montajı",
      "Raf montajı",
      "TV askı aparatı montajı",
      "Perde asma",
      "Stor perde montajı",
      "Korniş montajı",
      "Ayna asma",
      "Tablo asma",
      "Mutfak dolabı montajı",
      "Mobilya sökme",
      "Mobilya tamiri",
      "Kapı kolu değişimi",
      "Menteşe ayarı",
      "Çekmece rayı değişimi",
    ],
  },
  {
    id: "tamir",
    label: "Küçük Tamir & Tadilat",
    emoji: "🔧",
    skills: [
      "Duvar delme",
      "Dübel / vida montajı",
      "Duvar tamiri",
      "Alçı / sıva tamiri",
      "Silikon çekme",
      "Fayans değişimi",
      "Parke tamiri",
      "Laminat döşeme",
      "Kapı tamiri",
      "Kapı montajı",
      "Kilit değişimi",
      "Çilingir işleri",
      "Pencere tamiri",
      "Cam değişimi",
      "Sineklik montajı",
      "Panjur tamiri",
      "Tavan tamiri",
      "Su yalıtımı",
      "Isı yalıtımı",
      "Alçıpan işleri",
    ],
  },
  {
    id: "boya",
    label: "Boya & Dekorasyon",
    emoji: "🎨",
    skills: [
      "Duvar boyama",
      "Tavan boyama",
      "Dış cephe boyama",
      "Kapı / pencere boyama",
      "Duvar kağıdı yapıştırma",
      "Dekoratif sıva",
      "Ahşap boyama & vernik",
      "Radyatör boyama",
      "Alçı kartonpiyer",
      "Duvar temizleme & astar",
      "Kalıp / bordür montajı",
      "İç mimari danışmanlık",
    ],
  },
  {
    id: "beyaz-esya",
    label: "Beyaz Eşya & Elektronik",
    emoji: "🔌",
    skills: [
      "Çamaşır makinesi tamiri",
      "Bulaşık makinesi tamiri",
      "Buzdolabı tamiri",
      "Fırın / ocak montajı",
      "Davlumbaz montajı",
      "Klima montajı",
      "Klima bakımı",
      "Televizyon kurulumu",
      "Uydu / çanak anten ayarı",
      "Modem & internet kurulumu",
      "Wi-Fi ağ kurulumu",
      "Bilgisayar tamiri",
      "Yazıcı kurulumu",
      "Telefon / tablet tamiri",
      "Akıllı ev sistemleri kurulumu",
      "Güvenlik kamerası montajı",
      "Alarm sistemi kurulumu",
      "Küçük ev aleti tamiri",
    ],
  },
  {
    id: "tasima",
    label: "Taşıma & Nakliyat",
    emoji: "📦",
    skills: [
      "Taşıma yardımı",
      "Evden eve nakliyat",
      "Ofis taşıma",
      "Eşya paketleme",
      "Ağır yük taşıma",
      "Şehir içi kurye",
      "Motorlu kurye",
      "Kamyonet ile taşıma",
      "Depo düzenleme",
      "Hurda / moloz taşıma",
      "Piyano / kasa taşıma",
      "Asansörlü taşıma",
    ],
  },
  {
    id: "temizlik",
    label: "Temizlik",
    emoji: "🧹",
    skills: [
      "Ev temizliği",
      "Ofis temizliği",
      "İnşaat sonrası temizlik",
      "Cam temizliği",
      "Halı yıkama",
      "Koltuk yıkama",
      "Yatak / şilte temizliği",
      "Dezenfeksiyon",
      "Böcek ilaçlama",
      "Baca temizliği",
      "Klima filtre temizliği",
      "Ütü & çamaşır yardımı",
      "Bahçe temizliği",
      "Araç içi detaylı temizlik",
    ],
  },
  {
    id: "bahce",
    label: "Bahçe & Dış Mekan",
    emoji: "🌿",
    skills: [
      "Çim biçme",
      "Ağaç budama",
      "Bahçe bakımı",
      "Peyzaj düzenleme",
      "Çit / tel örgü montajı",
      "Kamelya / pergola kurulumu",
      "Bitki dikimi",
      "Saksı & balkon düzenleme",
      "Havuz bakımı",
      "Kar temizleme",
      "Barbekü kurulumu",
      "Ahşap deck döşeme",
    ],
  },
  {
    id: "arac",
    label: "Araç & Ulaşım",
    emoji: "🚗",
    skills: [
      "Lastik değişimi",
      "Akü takviyesi",
      "Araç yıkama",
      "Oto elektrik",
      "Küçük araç tamiri",
      "Araç teslim / getir götür",
      "Şoförlük",
      "Bisiklet tamiri",
      "Motosiklet tamiri",
      "Çekici yardımı",
    ],
  },
  {
    id: "usta",
    label: "Ustalık & Zanaat",
    emoji: "🛠️",
    skills: [
      "Marangozluk",
      "Ahşap işleri",
      "Kaynak işleri",
      "Demir doğrama",
      "Alüminyum doğrama",
      "PVC doğrama",
      "Duvar ustalığı",
      "Sıvacılık",
      "Fayans ustalığı",
      "Mermer / granit işleri",
      "Çatı tamiri",
      "Oluk montajı",
      "Asansör bakımı",
      "Doğalgaz tesisatı",
      "Isıtma & soğutma sistemleri",
    ],
  },
  {
    id: "etkinlik",
    label: "Etkinlik & Organizasyon",
    emoji: "🎉",
    skills: [
      "Etkinlik kurulumu",
      "Masa & sandalye dizimi",
      "Balon süsleme",
      "Doğum günü organizasyonu",
      "Ses sistemi kurulumu",
      "Işık sistemi kurulumu",
      "Sahne kurulumu",
      "Fotoğraf çekimi",
      "Video çekimi",
      "Garsonluk",
      "Barista / ikram",
      "Çadır & tente kurulumu",
    ],
  },
  {
    id: "kisisel",
    label: "Kişisel Yardım & Bakım",
    emoji: "🤝",
    skills: [
      "Alışveriş yardımı",
      "Market alışverişi",
      "Sıra bekleme",
      "Yaşlı refakat",
      "Çocuk bakımı",
      "Evcil hayvan bakımı",
      "Köpek gezdirme",
      "Yemek yapma yardımı",
      "Kuaförlük",
      "Berberlik",
      "Manikür & pedikür",
      "Masaj",
      "Kişisel antrenörlük",
      "Diyet danışmanlığı",
    ],
  },
  {
    id: "egitim",
    label: "Eğitim & Danışmanlık",
    emoji: "📚",
    skills: [
      "Özel ders (matematik)",
      "Özel ders (fen)",
      "Özel ders (İngilizce)",
      "Yabancı dil dersi",
      "Müzik dersi",
      "Gitar dersi",
      "Piyano dersi",
      "Bilgisayar eğitimi",
      "Kodlama dersi",
      "Ödev yardımı",
      "Sınav hazırlık",
      "Sürücü kursu desteği",
      "Muhasebe danışmanlığı",
      "Vergi & beyanname yardımı",
      "Hukuki danışmanlık",
      "Sigorta danışmanlığı",
    ],
  },
  {
    id: "ofis",
    label: "Ofis & Dijital İşler",
    emoji: "💼",
    skills: [
      "Veri girişi",
      "Belge düzenleme",
      "Excel işleri",
      "Sunum hazırlama",
      "Çeviri",
      "Metin yazarlığı",
      "Sosyal medya yönetimi",
      "Grafik tasarım",
      "Logo tasarımı",
      "Web sitesi kurulumu",
      "E-ticaret ürün girişi",
      "Video düzenleme",
      "Fotoğraf düzenleme",
      "Telefonla müşteri desteği",
      "Randevu & takvim yönetimi",
      "Kargo / evrak takibi",
    ],
  },
];

export const ALL_SKILLS: string[] = SKILL_GROUPS.flatMap((g) => g.skills);

const normalize = (value: string) =>
  value
    .toLocaleLowerCase("tr-TR")
    .replaceAll("ı", "i")
    .replaceAll("ş", "s")
    .replaceAll("ğ", "g")
    .replaceAll("ü", "u")
    .replaceAll("ö", "o")
    .replaceAll("ç", "c")
    .trim();

export const searchSkills = (query: string): SkillGroup[] => {
  const q = normalize(query);
  if (!q) return SKILL_GROUPS;
  return SKILL_GROUPS.map((g) => ({
    ...g,
    skills: g.skills.filter((s) => normalize(s).includes(q)),
  })).filter((g) => g.skills.length > 0);
};
