REVOKE EXECUTE ON FUNCTION public.charge_credit_on_task_create() FROM anon, authenticated, public;
REVOKE EXECUTE ON FUNCTION public.charge_credit_on_assignment() FROM anon, authenticated, public;
REVOKE EXECUTE ON FUNCTION public.enforce_single_active_assignment() FROM anon, authenticated, public;
REVOKE EXECUTE ON FUNCTION public.bump_completed_counts() FROM anon, authenticated, public;
REVOKE EXECUTE ON FUNCTION public.notify_assignment_event() FROM anon, authenticated, public;
REVOKE EXECUTE ON FUNCTION public.recalc_profile_rating() FROM anon, authenticated, public;
REVOKE EXECUTE ON FUNCTION public.sync_task_fill_status() FROM anon, authenticated, public;
REVOKE EXECUTE ON FUNCTION public.handle_new_user() FROM anon, authenticated, public;
REVOKE EXECUTE ON FUNCTION public.update_updated_at_column() FROM anon, authenticated, public;